### PR TITLE
Challenges now have visible goals

### PR DESCRIPTION
**Pull request by James103**
Each challenge now displays its goal, which is the minimum required amount of the challenge stat (happiness, income, and game speed respectively for the first 3 challenges) that will allow completing the challenge to increase the reward.

Furthermore, a display error in Time Warping has been fixed (reproducible while running the 3rd challenge).

### CODE REVIEW

**Comment by thomaspj10** [comment]
Can you provide a screenshot? I think this might get a bit verbose

**Comment by James103** [comment]
<details>

<summary> What the new challenge goals look like, with some progress and all five challenges unlocked </summary>

image

</details>

**Comment by thomaspj10** [comment]
Can you merge main into this branch again? :)

**Comment by James103** [comment]
> Can you merge main into this branch again? :)

I'm working on it and will let you know when done.

**Comment by James103** [comment]
> > Can you merge main into this branch again? :)
> 
> I'm working on it and will let you know when done.

I've finished updating the branch; see the previous comment for more details.

**Comment by thomaspj10** [comment]
Thanks! Really happy with the PRs you are making :D

**Pull request merged**
